### ISSUE TITLE
Atom 1.13 deprecates shadow DOM selectors

### ISSUE THREAD

**Issue by freinbichler** [paradox41/itg-dark-syntax#4]
Atom 1.13 deprecates the use of shadow DOM selectors.
Reference: http://blog.atom.io/2017/01/10/atom-1-13.html

[This blog post](http://blog.atom.io/2016/11/14/removing-shadow-dom-boundary-from-text-editor-elements.html) details which changes are needed.

**Comment by paradox41** [comment]
This repo is no longer maintained. If you would like to make a PR, I'd likely accept it. I'd encourage you to look at the [official theme](https://github.com/itsthatguy/atom-itg-flat).
